### ISSUE TITLE
How are tsv files created?

### ISSUE THREAD

**Issue by KinWaiCheuk** [jongwook/onsets-and-frames#11]
If I am not wrong, you store all the annotations to tsv files, and you load the labels directly from these tsv files.

If I have my own dataset with only .midi files, how do I get these annotations? Do you have the scripts to do .midi to tsv files conversions?

**Comment by jongwook** [comment]
Related code is in [midi.py](https://github.com/jongwook/onsets-and-frames/blob/master/onsets_and_frames/midi.py#L87-L106), although there seems to be some problem (see #3) in that implementation regarding the sustain pedal. Use at your own risk! :D
