### ISSUE TITLE
What is the reason of reading audio as int16 instead of float?

### ISSUE THREAD

**Issue by KinWaiCheuk** [jongwook/onsets-and-frames#14]
In your `dataset.py` at line 98, you use soundfile to read the audio as `int16`.
Later during `__getitem__` at line 51, you convert the int16 tensor into a float tensor.

Why don't we just read the audio as `float` directly with soundfile?

**Comment by jongwook** [comment]
To save the runtime memory usage by 2x, which allows loading the entire MAESTRO (v1) dataset in a 32GB machine.
