### ISSUE TITLE
How to run inference on single wav file?

### ISSUE THREAD

**Issue by JasonMathewsUCB** [jongwook/onsets-and-frames#15]
When I try using transcribe.py to run inference on a single wav file it throws me ` Error opening '/home/Jason/TestFlac/': File contains data in an unknown format.`

**Comment by jongwook** [comment]
What exact command line did you use? Also, it'll help if you paste the full stack trace of your error.

**Comment by JasonMathewsUCB** [comment]
Below is the command and full stack of error message.

`python transcribe.py /home/Jason/onsets-and-frames/runs/transcriber-200202-225454/model-321000.pt /home/Jason/TestFlac/MIDI-Unprocessed_01_R1_2006_01-09_ORIG_MID--AUDIO_01_R1_2006_01_Track01_wav.wav`


```
Processing /home/Jason/TestFlac/MIDI-Unprocessed_01_R1_2006_01-09_ORIG_MID--AUDIO_01_R1_2006_01_Track01_wav.wav...
Traceback (most recent call last):
  File "transcribe.py", line 89, in <module>
    transcribe_file(**vars(parser.parse_args()))
  File "transcribe.py", line 61, in transcribe_file
    audio = load_and_process_audio(flac_path, sequence_length, device)
  File "transcribe.py", line 17, in load_and_process_audio
    assert sr == SAMPLE_RATE
AssertionError
```

**Comment by jongwook** [comment]
This specific bug is happening because the WAV file is not in 16kHz sample rate. Try:

```
ffmpeg -i /home/Jason/TestFlac/MIDI-Unprocessed_01_R1_2006_01-09_ORIG_MID--AUDIO_01_R1_2006_01_Track01_wav.wav /home/Jason/TestFlac/MIDI-Unprocessed_01_R1_2006_01-09_ORIG_MID--AUDIO_01_R1_2006_01_Track01_wav.16k.wav
```

to convert the WAV file(s) to 16kHz and run `transcribe.py` with that file.

**Comment by JasonMathewsUCB** [comment]
Tried that but still the error persists. 
`python transcribe.py /home/Jason/onsets-and-frames/runs/transcriber-200202-225454/model-321000.pt /home/Jason/TestFlac/MIDI-Unprocessed_01_R1_2006_01-09_ORIG_MID--AUDIO_01_R1_2006_01_Track01_wav.16k.wav`



```
Processing /home/Jason/TestFlac/MIDI-Unprocessed_01_R1_2006_01-09_ORIG_MID--AUDIO_01_R1_2006_01_Track01_wav.16k.wav...
Traceback (most recent call last):
  File "transcribe.py", line 89, in <module>
    transcribe_file(**vars(parser.parse_args()))
  File "transcribe.py", line 61, in transcribe_file
    audio = load_and_process_audio(flac_path, sequence_length, device)
  File "transcribe.py", line 17, in load_and_process_audio
    assert sr == SAMPLE_RATE
AssertionError

```

**Comment by jongwook** [comment]
Oops, I wrote the wrong ffmpeg command line; it should be:

```
ffmpeg -i /home/Jason/TestFlac/MIDI-Unprocessed_01_R1_2006_01-09_ORIG_MID--AUDIO_01_R1_2006_01_Track01_wav.wav -ac 1 -ar 16000 /home/Jason/TestFlac/MIDI-Unprocessed_01_R1_2006_01-09_ORIG_MID--AUDIO_01_R1_2006_01_Track01_wav.16k.wav
```

**Comment by JasonMathewsUCB** [comment]
Yeah, that works!! Thanks.
