### ISSUE TITLE
Linter/formatter?

### ISSUE THREAD

**Issue by brianc118** [jongwook/onsets-and-frames#19]
Is there a standard linter / formatter that you're using @jongwook?

Thanks!

**Comment by jongwook** [comment]
Hi I wasn't diligent enough to use one. I have the default PEP8 warnings turned on in IntelliJ with an exception of allowing 120-character columns. But I didn't enforce that using a build script or a hook.

**Comment by brianc118** [comment]
Ok cool thanks!
