### ISSUE TITLE
Can this project convert wav format files into mid files?

### ISSUE THREAD

**Issue by YuHsin1998** [jongwook/onsets-and-frames#2]

**Comment by jongwook** [comment]
Hi, the codebase has the dataset creation and training/evaluation part, but it doesn't come with pre-trained weights or scripts for running them.

You can train a model yourself and hack with [evaluate.py] to create a transcriber.

I'll leave this issue open as a future reference for when I can add an out-of-the-box transcriber script.

In the meantime, you can use Google's onsets and frames implementation to create MIDI files from WAV files.

**Comment by YuHsin1998** [comment]
Thank you so much！
After listening to your suggestions, I run this program. After the program iterated 2500 times, the following error occurred.Any reason why this is happening?

ERROR - train_transcriber - Failed after 0:23:28!
Traceback (most recent calls WITHOUT Sacred internals):
  File "train.py", line 106, in train
    for key, value in evaluate(validation_dataset, model).items():
  File "/home/zhaoyuxin/onsets-and-frames/evaluate.py", line 76, in evaluate
    p, r, f, o = evaluate_notes_with_velocity(i_ref, p_ref, v_ref, i_est, p_est, v_est, velocity_tolerance=0.1)
  File "/home/zhaoyuxin/.local/lib/python3.5/site-packages/mir_eval/transcription_velocity.py", line 291, in precision_recall_f1_overlap
    offset_min_tolerance, strict, velocity_tolerance)
  File "/home/zhaoyuxin/.local/lib/python3.5/site-packages/mir_eval/transcription_velocity.py", line 178, in match_notes
    ref_matched_velocities = ref_velocities[matching[:, 0]]
IndexError: too many indices for array

Before the mistake occur，the shape of i_ref,p_ref,v_ref,i_est,p_est,v_est are :
(111, 2)
(111,)
(111,)
(36, 2)
(36,)
(36,)

**Comment by jongwook** [comment]
Hi, this is probably related to #1 . You can install the latest mir_eval with

```
pip uninstall mir_eval
pip install git+https://github.com/craffel/mir_eval.git
```

**Comment by YuHsin1998** [comment]
Thank you very much!
